In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('/content/turbo_az - turbo_az.csv')
df

,Avtosalon,Qiymet,Valyuta,Şəhər,Marka,Model,Buraxılış ili,Ban növü,Rəng,Mühərrik,...,Yeni,Vəziyyəti,Yeniləndi,Baxışların sayı,Extra,Etrafli,Sahiblər,Hansı bazar üçün yığılıb,Yerlərin sayı,Qəzalı
0,0,13500,AZN,Bakı,Opel,Vectra,2000,Hetçbek,Göy,1.6 L/101 a.g./Benzin,...,Xeyr,"Vuruğu yoxdur, rənglənib",28.05.2023,267,"Yüngül lehimli disklər, ABS, Kondisioner, Dəri...",Salam Barter mümkündür. 1.6 sadə mator mexanik...,2,Avropa,5,NaN
1,1,23500,USD,Bakı,Toyota,Corolla,2023,Sedan,Mavi,1.8 L/178 a.g./Hibrid,...,Bəli,"Vuruğu yoxdur, rənglənməyib",28.05.2023,12410,"Yüngül lehimli disklər, ABS, Yağış sensoru, Mə...",TOYOTA CAROLLA 2023 ALIŞ. 2 İL 80.000 KM ZƏMAN...,1,Rəsmi diler,5,NaN
2,0,33200,AZN,Bakı,Hyundai,Santa Fe,2013,Offroader / SUV,Qara,2.0 L/184 a.g./Dizel,...,Xeyr,"Vuruğu yoxdur, rənglənməyib",28.05.2023,148,"Yüngül lehimli disklər, ABS, Lyuk, Yağış senso...",Yeni gelib bakida surlmuyb qiymet mawin yanind...,1,Avropa,7,NaN
3,0,17000,AZN,Bakı,Ford,Fusion,2015,Sedan,Göy,1.5 L/181 a.g./Benzin,...,Xeyr,"Vuruğu yoxdur, rənglənməyib",25.05.2023,3358,"Yüngül lehimli disklər, ABS, Yağış sensoru, Mə...",Maşın xanım tərəfindən idarə olunub,NaN,NaN,NaN,NaN
4,0,36000,USD,Bakı,Toyota,RAV4,2022,Offroader / SUV,Qara,2.0 L/173 a.g./Benzin,...,Bəli,"Vuruğu yoxdur, rənglənməyib",28.05.2023,16183,"Yüngül lehimli disklər, ABS, Yağış sensoru, Mə...",Rəsmi dilerdən 10 il və ya 160.000 km zəmanəti...,1,NaN,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,22900,USD,Bakı,BMW,528,2016,Sedan,Qara,2.0 L/245 a.g./Benzin,...,Xeyr,"Vuruğu yoxdur, rənglənməyib",28.05.2023,1202,"Yüngül lehimli disklər, ABS, Lyuk, Yağış senso...",Avtomobil cox ela veziyyetdedir. Azerbaycana g...,2,NaN,5,NaN
9996,0,98000,USD,Bakı,Land Rover,Range Rover,2019,Offroader / SUV,Qara,3.0 L/340 a.g./Benzin,...,Xeyr,"Vuruğu yoxdur, rənglənməyib",27.05.2023,1144,"Yüngül lehimli disklər, ABS, Lyuk, Yağış senso...",Avtomobil ideal veziyyetdedir Yeniden secilmi...,NaN,NaN,NaN,NaN
9997,0,9800,AZN,Bakı,Chevrolet,Lacetti,2007,Sedan,Gümüşü,1.6 L/109 a.g./Benzin,...,Xeyr,"Vuruğu yoxdur, rənglənməyib",26.05.2023,552,"Yüngül lehimli disklər, ABS, Mərkəzi qapanma, ...",Salam . Masinin ancag yungul kasmetikaya ehdiy...,NaN,Koreya,5,NaN
9998,0,17800,AZN,Bakı,Hyundai,Tucson,2007,Offroader / SUV,Gümüşü,2.0 L/140 a.g./Dizel,...,Xeyr,"Vuruğu yoxdur, rənglənməyib",27.05.2023,317,"Yüngül lehimli disklər, ABS, Yağış sensoru, Mə...","Avtomobil ideal vəziyyətdədir , heç bir proble...",1,Avropa,5,NaN
9999,0,5000,AZN,Gəncə,LADA (VAZ),2107,2004,Sedan,Ağ,1.6 L/75 a.g./Benzin,...,Xeyr,"Vuruğu yoxdur, rənglənməyib",26.05.2023,381,Yüngül lehimli disklər,Rasxodlar ödənilib,NaN,Digər,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Avtosalon                 10000 non-null  int64
 1   Qiymet                    10000 non-null  int64
 2   Valyuta                   10000 non-null  object
 3   Şəhər                     10000 non-null  object
 4   Marka                     10000 non-null  object
 5   Model                     10000 non-null  object
 6   Buraxılış ili             10000 non-null  int64
 7   Ban növü                  10000 non-null  object
 8   Rəng                      10000 non-null  object
 9   Mühərrik                  10000 non-null  object
 10  Yürüş                     10000 non-null  object
 11  Sürətlər qutusu           10000 non-null  object
 12  Ötürücü                   10000 non-null  object
 13  Yeni                      10000 non-null  object
 14  Vəziyyəti                 9972 non-null   object
 15  Yeniləndi                 10000 non-null  object
 16  Baxışların sayı           10000 non-null  int64
 17  Extra                     9236 non-null   object
 18  Etrafli                   9718 non-null   object
 19  Sahiblər                  6193 non-null   object
 20  Hansı bazar üçün yığılıb  6702 non-null   object
 21  Yerlərin sayı             6832 non-null   object
 22  Qəzalı                    32 non-null     object
dtypes: int64(4), object(19)
memory usage: 1.8+ MB

In [ ]:
#Preprocessing

In [4]:
df.isnull().sum()

Avtosalon                      0
Qiymet                         0
Valyuta                        0
Şəhər                          0
Marka                          0
Model                          0
Buraxılış ili                  0
Ban növü                       0
Rəng                           0
Mühərrik                       0
Yürüş                          0
Sürətlər qutusu                0
Ötürücü                        0
Yeni                           0
Vəziyyəti                     28
Yeniləndi                      0
Baxışların sayı                0
Extra                        764
Etrafli                      282
Sahiblər                    3807
Hansı bazar üçün yığılıb    3298
Yerlərin sayı               3168
Qəzalı                      9968
dtype: int64

In [5]:
df.columns.tolist()

['Avtosalon',
 'Qiymet',
 'Valyuta',
 'Şəhər',
 'Marka',
 'Model',
 'Buraxılış ili',
 'Ban növü',
 'Rəng',
 'Mühərrik',
 'Yürüş',
 'Sürətlər qutusu',
 'Ötürücü',
 'Yeni',
 'Vəziyyəti',
 'Yeniləndi',
 'Baxışların sayı',
 'Extra',
 'Etrafli',
 'Sahiblər',
 'Hansı bazar üçün yığılıb',
 'Yerlərin sayı',
 'Qəzalı']

In [6]:
def extract_currency(text):
    if pd.isna(text):
        return np.nan
    text = str(text).upper()
    if 'USD' in text:
        return 'USD'
    elif 'AZN' in text:
        return 'AZN'
    elif 'EUR' in text:
        return 'EUR'
    return 'AZN'

In [7]:
def extract_price_number(text):
    if pd.isna(text):
        return np.nan
    clean_text = ''.join(c for c in str(text) if c.isdigit() or c == '.' or c == ',')
    clean_text = clean_text.replace(',', '')
    try:
        return float(clean_text)
    except:
        return np.nan

In [8]:
df['Valyuta'] = df['Qiymet'].apply(extract_currency)
df['Təmiz_Qiymət'] = df['Qiymet'].apply(extract_price_number)

In [9]:
def convert_to_azn(row):
    price = row['Təmiz_Qiymət']
    currency = row['Valyuta']
    if pd.isna(price):
        return np.nan
    if currency == 'USD':
        return price * 1.70
    elif currency == 'EUR':
        return price * 1.85
    else:
        return price

In [10]:
df['Target_Qiymet_AZN'] = df.apply(convert_to_azn, axis=1)

In [11]:
df[['Qiymet', 'Valyuta', 'Təmiz_Qiymət', 'Target_Qiymet_AZN']].head()

   Qiymet Valyuta  Təmiz_Qiymət  Target_Qiymet_AZN
0   13500     AZN       13500.0            13500.0
1   23500     AZN       23500.0            23500.0
2   33200     AZN       33200.0            33200.0
3   17000     AZN       17000.0            17000.0
4   36000     AZN       36000.0            36000.0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Avtosalon                 10000 non-null  int64
 1   Qiymet                    10000 non-null  int64
 2   Valyuta                   10000 non-null  object
 3   Şəhər                     10000 non-null  object
 4   Marka                     10000 non-null  object
 5   Model                     10000 non-null  object
 6   Buraxılış ili             10000 non-null  int64
 7   Ban növü                  10000 non-null  object
 8   Rəng                      10000 non-null  object
 9   Mühərrik                  10000 non-null  object
 10  Yürüş                     10000 non-null  object
 11  Sürətlər qutusu           10000 non-null  object
 12  Ötürücü                   10000 non-null  object
 13  Yeni                      10000 non-null  object
 14  Vəziyyəti                 9972 non-null   object
 15  Yeniləndi                 10000 non-null  object
 16  Baxışların sayı           10000 non-null  int64
 17  Extra                     9236 non-null   object
 18  Etrafli                   9718 non-null   object
 19  Sahiblər                  6193 non-null   object
 20  Hansı bazar üçün yığılıb  6702 non-null   object
 21  Yerlərin sayı             6832 non-null   object
 22  Qəzalı                    32 non-null     object
 23  Təmiz_Qiymət              10000 non-null  float64
 24  Target_Qiymet_AZN         10000 non-null  float64
dtypes: float64(2), int64(4), object(19)
memory usage: 1.9+ MB

In [ ]:
#Mühərrik sütununu qaydaya salırıq

In [13]:
engine_split = df['Mühərrik'].str.split('/', expand=True)

In [14]:
df['Muhərrik_Həcmi_Raw'] = engine_split[0]
df['At_Gucü_Raw'] = engine_split[1]
df['Yanacaq_Novu'] = engine_split[2]

In [15]:
df['Muhərrik_Həcmi'] = df['Muhərrik_Həcmi_Raw'].str.replace('L', '', case=False).str.strip()
df['Muhərrik_Həcmi'] = pd.to_numeric(df['Muhərrik_Həcmi'], errors='coerce')

In [16]:
df['At_Gucü'] = df['At_Gucü_Raw'].str.replace('a.g.', '', case=False).str.strip()
df['At_Gucü'] = pd.to_numeric(df['At_Gucü'], errors='coerce')

In [17]:
df['Yanacaq_Novu'] = df['Yanacaq_Novu'].str.strip()

In [18]:
df = df.drop(columns=['Muhərrik_Həcmi_Raw', 'At_Gucü_Raw'])

In [19]:
df[['Mühərrik', 'Muhərrik_Həcmi', 'At_Gucü', 'Yanacaq_Novu']].head()

                Mühərrik  Muhərrik_Həcmi  At_Gucü Yanacaq_Novu
0  1.6 L/101 a.g./Benzin             1.6      101       Benzin
1  1.8 L/178 a.g./Hibrid             1.8      178       Hibrid
2   2.0 L/184 a.g./Dizel             2.0      184        Dizel
3  1.5 L/181 a.g./Benzin             1.5      181       Benzin
4  2.0 L/173 a.g./Benzin             2.0      173       Benzin

In [20]:
engine_split = df['Mühərrik'].str.split('/', expand=True)

In [21]:
df['Engine_Volume_Raw'] = engine_split[0].str.strip()
df['HP_Raw'] = engine_split[1].str.strip()
df['Fuel_Type_Raw'] = engine_split[2].str.strip()

In [22]:
df['Engine_Volume'] = df['Engine_Volume_Raw'].str.replace('L', '', case=False).str.strip()

In [23]:
df['Engine_Volume'] = pd.to_numeric(df['Engine_Volume'], errors='coerce')

In [24]:
df['HP'] = df['HP_Raw'].str.replace('a.g.', '', case=False).str.strip()

In [25]:
df['HP'] = pd.to_numeric(df['HP'], errors='coerce')

In [26]:
df['Fuel_Type'] = df['Fuel_Type_Raw'].str.strip()

In [27]:
df = df.drop(columns=['Engine_Volume_Raw', 'HP_Raw', 'Fuel_Type_Raw'])

In [28]:
df.isnull().sum()

Avtosalon                      0
Qiymet                         0
Valyuta                        0
Şəhər                          0
Marka                          0
Model                          0
Buraxılış ili                  0
Ban növü                       0
Rəng                           0
Mühərrik                       0
Yürüş                          0
Sürətlər qutusu                0
Ötürücü                        0
Yeni                           0
Vəziyyəti                     28
Yeniləndi                      0
Baxışların sayı                0
Extra                        764
Etrafli                      282
Sahiblər                    3807
Hansı bazar üçün yığılıb    3298
Yerlərin sayı               3168
Qəzalı                      9968
Təmiz_Qiymət                   0
Target_Qiymet_AZN              0
Yanacaq_Novu                   0
Muhərrik_Həcmi                 0
At_Gucü                        0
Engine_Volume                  0
HP                             0
Fuel_Type                      0
dtype: int64

In [ ]:
#NaN dəyərləri təmizləyirik

In [29]:
df['HP'] = df.groupby(['Marka', 'Model'])['HP'].transform(lambda x: x.fillna(x.median()))

In [30]:
df['Engine_Volume'] = df.groupby(['Marka', 'Model'])['Engine_Volume'].transform(lambda x: x.fillna(x.median()))

In [31]:
df['HP'] = df['HP'].fillna(df['HP'].median())
df['Engine_Volume'] = df['Engine_Volume'].fillna(df['Engine_Volume'].median())

In [32]:
df['Yerlərin sayı'] = df['Yerlərin sayı'].fillna(df['Yerlərin sayı'].mode()[0])

In [33]:
df['Sahiblər'] = df['Sahiblər'].fillna('Melum deyil')

In [34]:
df['Hansı bazar üçün yığılıb'] = df['Hansı bazar üçün yığılıb'].fillna('Melum deyil')

In [35]:
df['Qəzalı'] = df['Qəzalı'].fillna('Xeyr')

In [ ]:
#Encoding

In [36]:
small_categorical = ['Ban növü', 'Rəng', 'Fuel_Type', 'Hansı bazar üçün yığılıb', 'Vəziyyəti', 'Sahiblər', 'Qəzalı', 'Yeni']

In [37]:
df = pd.get_dummies(df, columns=small_categorical, drop_first=True, dtype=int)

In [38]:
df['Marka_Encoded'] = df.groupby('Marka')['Target_Qiymet_AZN'].transform('mean')
df['Model_Encoded'] = df.groupby('Model')['Target_Qiymet_AZN'].transform('mean')

In [39]:
df = df.drop(columns=['Marka', 'Model'])

In [40]:
df['Extra'].unique()

array(['Yüngül lehimli disklər, ABS, Kondisioner, Dəri salon, Ksenon lampalar, Yan pərdələr',
       'Yüngül lehimli disklər, ABS, Yağış sensoru, Mərkəzi qapanma, Park radarı, Kondisioner, Oturacaqların isidilməsi, Ksenon lampalar, Arxa görüntü kamerası, Yan pərdələr, Oturacaqların ventilyasiyası',
       'Yüngül lehimli disklər, ABS, Lyuk, Yağış sensoru, Mərkəzi qapanma, Park radarı, Kondisioner, Oturacaqların isidilməsi, Dəri salon, Ksenon lampalar, Arxa görüntü kamerası, Yan pərdələr, Oturacaqların ventilyasiyası',
       ...,
       'ABS, Yağış sensoru, Kondisioner, Oturacaqların isidilməsi, Dəri salon',
       'Yüngül lehimli disklər, ABS, Mərkəzi qapanma, Park radarı, Kondisioner, Dəri salon, Arxa görüntü kamerası, Yan pərdələr, Oturacaqların ventilyasiyası',
       'Yüngül lehimli disklər, ABS, Lyuk, Mərkəzi qapanma, Kondisioner, Dəri salon, Ksenon lampalar, Yan pərdələr, Oturacaqların ventilyasiyası'],
      dtype=object)

In [ ]:
df['has_ABS'] = df['Extra'].str.contains('ABS', case=False, na=False).astype(int)
df['has_Kondisioner'] = df['Extra'].str.contains('Kondisioner', case=False, na=False).astype(int)
df['has_Lyuk'] = df['Extra'].str.contains('Lyuk', case=False, na=False).astype(int)
df['has_Yagish_Sensoru'] = df['Extra'].str.contains('Yağış sensoru', case=False, na=False).astype(int)
df['has_Deri_Salon'] = df['Extra'].str.contains('Dəri', case=False, na=False).astype(int)

In [41]:
df['has_Disdler'] = df['Extra'].str.contains('Yüngül lehimli disklər', case=False, na=False).astype(int)
df['has_Park_Radari'] = df['Extra'].str.contains('Park radarı', case=False, na=False).astype(int)
df['has_Oturacaq_Isidilmesi'] = df['Extra'].str.contains('Oturacaqların isidilməsi', case=False, na=False).astype(int)
df['has_Oturacaq_Ventilyasiyasi'] = df['Extra'].str.contains('Oturacaqların ventilyasiyası', case=False, na=False).astype(int)
df['has_Kamera'] = df['Extra'].str.contains('Arxa görüntü kamerası', case=False, na=False).astype(int)
df['has_Ksenon'] = df['Extra'].str.contains('Ksenon lampalar', case=False, na=False).astype(int)

In [42]:
df['Total_Extras_Count'] = df['Extra'].apply(lambda x: len(str(x).split(',')) if pd.notna(x) else 0)

In [43]:
df = df.drop(columns=['Extra'])

In [44]:
dff=df.drop(columns=['Yeniləndi'], errors='ignore')

In [45]:
dff.dtypes

Avtosalon                       int64
Qiymet                          int64
Valyuta                        object
Şəhər                          object
Buraxılış ili                   int64
                                ...
has_Oturacaq_Isidilmesi         int64
has_Oturacaq_Ventilyasiyasi     int64
has_Kamera                      int64
has_Ksenon                      int64
Total_Extras_Count              int64
Length: 85, dtype: object

In [46]:
dff.isnull().sum().sum()

np.int64(282)

In [47]:
dff.isnull().sum()[dff.isnull().sum() > 0]

Etrafli    282
dtype: int64

In [48]:
df= dff.drop(columns=['Etrafli', 'Extra', 'Yeniləndi'], errors='ignore')

In [49]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
#Outlier qaydaya salaq

In [50]:
original_size = len(df)

In [51]:
df = df[(df['Target_Qiymet_AZN'] >= 1000) & (df['Target_Qiymet_AZN'] <= 400000)]

In [52]:
df = df[(df['Buraxılış ili'] >= 1960) & (df['Buraxılış ili'] <= 2026)]

In [53]:
Q1 = df['HP'].quantile(0.25)
Q3 = df['HP'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [54]:
df = df[(df['HP'] >= lower_bound) & (df['HP'] <= upper_bound)]

In [55]:
cleaned_size = len(df)
r= original_size - cleaned_size

In [56]:
r

515

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
y = df['Target_Qiymet_AZN']

In [59]:
X = df.drop(columns=['Target_Qiymet_AZN', 'Qiymet', 'Təmiz_Qiymət'], errors='ignore')

In [60]:
X = X.select_dtypes(include=[np.number])

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [62]:
X.shape[1]

73

In [63]:
X.columns.tolist()

['Avtosalon',
 'Buraxılış ili',
 'Baxışların sayı',
 'Muhərrik_Həcmi',
 'At_Gucü',
 'Engine_Volume',
 'HP',
 'Ban növü_Dartqı',
 'Ban növü_Furqon',
 'Ban növü_Hetçbek',
 'Ban növü_Kabriolet',
 'Ban növü_Kupe',
 'Ban növü_Kvadrosikl',
 'Ban növü_Liftbek',
 'Ban növü_Mikroavtobus',
 'Ban növü_Minivan',
 'Ban növü_Moped',
 'Ban növü_Motosiklet',
 'Ban növü_Offroader / SUV',
 'Ban növü_Pikap',
 'Ban növü_Rodster',
 'Ban növü_Sedan',
 'Ban növü_Universal',
 'Ban növü_Van',
 'Ban növü_Yük maşını',
 'Rəng_Bej',
 'Rəng_Boz',
 'Rəng_Bənövşəyi',
 'Rəng_Göy',
 'Rəng_Gümüşü',
 'Rəng_Mavi',
 'Rəng_Narıncı',
 'Rəng_Qara',
 'Rəng_Qırmızı',
 'Rəng_Qızılı',
 'Rəng_Qəhvəyi',
 'Rəng_Sarı',
 'Rəng_Tünd qırmızı',
 'Rəng_Yaş Asfalt',
 'Rəng_Yaşıl',
 'Rəng_Çəhrayı',
 'Fuel_Type_Dizel',
 'Fuel_Type_Elektro',
 'Fuel_Type_Hibrid',
 'Fuel_Type_Plug-in Hibrid',
 'Fuel_Type_Qaz',
 'Hansı bazar üçün yığılıb_Avropa',
 'Hansı bazar üçün yığılıb_Digər',
 'Hansı bazar üçün yığılıb_Dubay',
 'Hansı bazar üçün yığılıb_Koreya',
 'Hansı bazar üçün yığılıb_Melum deyil',
 'Hansı bazar üçün yığılıb_Rusiya',
 'Hansı bazar üçün yığılıb_Rəsmi diler',
 'Hansı bazar üçün yığılıb_Yaponiya',
 'Vəziyyəti_Vuruğu var, rənglənməyib',
 'Vəziyyəti_Vuruğu yoxdur, rənglənib',
 'Vəziyyəti_Vuruğu yoxdur, rənglənməyib',
 'Sahiblər_1',
 'Sahiblər_2',
 'Sahiblər_3',
 'Sahiblər_4 və daha çox',
 'Sahiblər_Melum deyil',
 'Qəzalı_Xeyr',
 'Yeni_Xeyr',
 'Marka_Encoded',
 'Model_Encoded',
 'has_Disdler',
 'has_Park_Radari',
 'has_Oturacaq_Isidilmesi',
 'has_Oturacaq_Ventilyasiyasi',
 'has_Kamera',
 'has_Ksenon',
 'Total_Extras_Count']

In [ ]:
#Modellər

In [64]:
from sklearn.ensemble import (
    RandomForestRegressor,
    AdaBoostRegressor,
    GradientBoostingRegressor,
    VotingRegressor,
    StackingRegressor
)
from xgboost import XGBRegressor
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import pandas as pd

In [65]:
bagging_model = RandomForestRegressor(n_estimators=300, max_depth=12, random_state=42, n_jobs=-1)
bagging_model.fit(X_train, y_train)

RandomForestRegressor(max_depth=12, n_estimators=300, n_jobs=-1,
                      random_state=42)

In [66]:
boosting_model = GradientBoostingRegressor(n_estimators=300, learning_rate=0.05, max_depth=6, random_state=42)

In [67]:
boosting_model.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=0.05, max_depth=6, n_estimators=300,
                          random_state=42)

In [68]:
ada_sub = AdaBoostRegressor(n_estimators=100, random_state=42)
gb_sub = GradientBoostingRegressor(n_estimators=300, learning_rate=0.05, max_depth=6, random_state=42)
xgb_sub = XGBRegressor(n_estimators=500, learning_rate=0.05, max_depth=6, random_state=42)

In [69]:
mixed_estimators = [
    ('ada', ada_sub),
    ('gb', gb_sub),
    ('xgb', xgb_sub)
]

In [70]:
voting_model = VotingRegressor(estimators=mixed_estimators)

In [71]:
voting_model.fit(X_train, y_train)

VotingRegressor(estimators=[('ada',
                             AdaBoostRegressor(n_estimators=100,
                                               random_state=42)),
                            ('gb',
                             GradientBoostingRegressor(learning_rate=0.05,
                                                       max_depth=6,
                                                       n_estimators=300,
                                                       random_state=42)),
                            ('xgb',
                             XGBRegressor(base_score=None, booster=None,
                                          callbacks=None,
                                          colsample_bylevel=None,
                                          colsample_bynode=None,
                                          colsample_bytree=None, device=None,
                                          early_stopping_rounds...
                                          feature_weights=None, gamma=None,
                                          grow_policy=None,
                                          importance_type=None,
                                          interaction_constraints=None,
                                          learning_rate=0.05, max_bin=None,
                                          max_cat_threshold=None,
                                          max_cat_to_onehot=None,
                                          max_delta_step=None, max_depth=6,
                                          max_leaves=None,
                                          min_child_weight=None, missing=nan,
                                          monotone_constraints=None,
                                          multi_strategy=None, n_estimators=500,
                                          n_jobs=None, num_parallel_tree=None, ...))])

In [72]:
stacking_model = StackingRegressor(estimators=mixed_estimators, final_estimator=Ridge())

In [73]:
stacking_model.fit(X_train, y_train)

StackingRegressor(estimators=[('ada',
                               AdaBoostRegressor(n_estimators=100,
                                                 random_state=42)),
                              ('gb',
                               GradientBoostingRegressor(learning_rate=0.05,
                                                         max_depth=6,
                                                         n_estimators=300,
                                                         random_state=42)),
                              ('xgb',
                               XGBRegressor(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None, device=None,
                                            early_stopping_roun...
                                            grow_policy=None,
                                            importance_type=None,
                                            interaction_constraints=None,
                                            learning_rate=0.05, max_bin=None,
                                            max_cat_threshold=None,
                                            max_cat_to_onehot=None,
                                            max_delta_step=None, max_depth=6,
                                            max_leaves=None,
                                            min_child_weight=None, missing=nan,
                                            monotone_constraints=None,
                                            multi_strategy=None,
                                            n_estimators=500, n_jobs=None,
                                            num_parallel_tree=None, ...))],
                  final_estimator=Ridge())

In [74]:
preds = {
    "Bagging (Random Forest)": bagging_model.predict(X_test),
    "Boosting (Gradient Boost)": boosting_model.predict(X_test),
    "Voting Regressor (Mixed)": voting_model.predict(X_test),
    "Stacking Regressor (Mixed)": stacking_model.predict(X_test)
}

In [75]:
results_list = []

In [76]:
for model_name, y_pred in preds.items():
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

In [77]:
results_list.append({
        "Ansambl Modeli": model_name,
        "MAE": f"{mae:.2f} AZN",
        "RMSE": f"{rmse:.2f} AZN",
        "R² Score": f"{r2 * 100:.2f}%"
    })

In [78]:
results_df = pd.DataFrame(results_list)

In [79]:
results_df

               Ansambl Modeli          MAE         RMSE R² Score
0  Stacking Regressor (Mixed)  2794.78 AZN  5441.40 AZN   91.99%

In [80]:
display(results_df)

               Ansambl Modeli          MAE         RMSE R² Score
0  Stacking Regressor (Mixed)  2794.78 AZN  5441.40 AZN   91.99%